import type { Metadata } from "next";
import { Source_Sans_3, Manjari } from "next/font/google";
import { AuthProvider } from "@/providers/auth";
import { Header } from "@/components/shared/header";
import { cn } from "@/lib/utils";
import "./globals.css";

const source = Source_Sans_3({ subsets: ["latin"], variable: "--body-font" });
const manjari = Manjari({
	weight: ["100", "400", "700"],
	subsets: ["latin"],
	variable: "--display-font"
});

export const metadata: Metadata = {
	title: "Crunchyroll",
	description: "Generated by create next app"
};

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="pt-br"
			suppressHydrationWarning
			className={`${source.variable} ${manjari.variable}`}
		>
			<body className={cn("dark", source.variable)}>
				<AuthProvider>
					<Header />
					{children}
				</AuthProvider>
			</body>
		</html>
	);
}
